fix: Badge size mismatch
fossasia/badge-magic-android pull request #746
Opened 2021-01-08 11:34 UTC by akri16

Fixes #586

Changes:
1. Change everything to 44 x 11
2. Fix related errors and refactor

Screenshots for the change:

**Creating the clipart** 

![WhatsApp Image 2021-01-08 at 16 38 37 (1)](https://user-images.githubusercontent.com/54491362/104010539-a9484580-51d2-11eb-8d4b-687c4363c2ef.jpeg)

**Static view**

![WhatsApp Image 2021-01-08 at 16 38 37](https://user-images.githubusercontent.com/54491362/104010616-c715aa80-51d2-11eb-86be-f3305417651a.jpeg)

**Animated view**

https://user-images.githubusercontent.com/54491362/104010632-d137a900-51d2-11eb-94c2-d7005847e3a2.mp4

**Normal Cliparts**

![WhatsApp Image 2021-01-08 at 16 45 05](https://user-images.githubusercontent.com/54491362/104010782-14921780-51d3-11eb-952a-c1a9f6ed56fd.jpeg)

2021-01-10 20:32 UTC, adityastic requested changes

2021-01-10 20:32 UTC, adityastic commented on android/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
> +import timber.log.Timber
This file can be rolled back

2021-01-10 20:32 UTC, adityastic commented on android/src/main/java/org/fossasia/badgemagic/util/Converters.kt
> +        Timber.d("$height $width")
Logging, can be removed

2021-01-10 20:32 UTC, adityastic commented on android/src/main/res/values/integers.xml
> +    <integer name="clip_viewport_width">44</integer>
Not sure if this is used

2021-01-10 20:32 UTC, adityastic commented on android/src/main/java/org/fossasia/badgemagic/util/Converters.kt
> +import timber.log.Timber
Same, timber. Logging can be removed

2021-01-10 20:32 UTC, adityastic commented on android/src/main/java/org/fossasia/badgemagic/ui/custom/PreviewBadge.kt
> +        Timber.d("$allHex")
Can be rolled back

2021-01-11 08:35 UTC, akri16 commented
I`ve made the requested changes and force pushed it after amending the commit. But I'm unable to 'Resolve Conversation' these requests. Is there a cleaner way to do the same?

2021-01-11 08:44 UTC, adityastic approved these changes
Lgtm

2021-01-11 08:45 UTC, merged

2021-01-11 08:48 UTC, adityastic commented
> Is there a cleaner way to do the same?
>
Once the new changes are detected. The comments on the last changes automatically get resolved